pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "demishuaccha/tingeso-m-frontend"
        DOCKER_TAG = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/tu-repo/tingeso-m-frontend.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh """
                    docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
                    """
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-cred', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh """
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push $DOCKER_IMAGE:$DOCKER_TAG
                        """
                    }
                }
            }
        }

        stage('Deploy with Docker Compose') {
            steps {
                script {
                    sh """
                    docker-compose down
                    docker-compose pull
                    docker-compose up -d
                    """
                }
            }
        }
    }

    post {
        success {
            echo " Deploy exitoso: $DOCKER_IMAGE:$DOCKER_TAG corriendo con docker-compose"
        }
        failure {
            echo " Algo falló en el pipeline"
        }
    }
}
