pipeline {
    agent any

    environment {
        IMAGE_NAME = "demishuaccha/frontend"
        IMAGE_TAG  = "latest"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    runCmd("""
                        docker build -t demishuaccha/frontend:latest -f monolitic-front/Dockerfile monolitic-front
                    """)
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    runCmd("""
                        docker push ${IMAGE_NAME}:${IMAGE_TAG}
                    """)
                }
            }
        }

        stage('Deploy with Docker Compose') {
            steps {
                script {
                    runCmd("""
                        docker compose down
                        docker compose up -d --build
                    """)
                }
            }
        }
    }

    post {
        failure {
            echo "Algo falló en el pipeline"
        }
    }
}

def runCmd(cmd) {
    if (isUnix()) {
        sh cmd
    } else {
        bat cmd
    }
}

